database:
  type: mysql
  host: account_service_database-0
  port: 3306
  username: root
  password: root
  database: db_account_service
grpc:
  address: 0.0.0.0
  port: 11001
auth:
  hash:
    cost: 10
log:
  level: debug
