http:
  address: 0.0.0.0
  port: 8080

auth:
  domain: localhost
  token:
    secret: "secret_token_in_here"
    accessTokenTTL: 15m
    refreshTokenTTL: 24h
    refreshTokenLongTTL: 720h

grpc:
  account_service:
    address: account_service-0
    port: 11001

cache:
  type: redis
  address: redis-0
  port: 6379
  username: ""
  password: ""

log:
  level: debug
